/** Minimum / maximum languages a user must pick during onboarding. */
export const ONBOARDING_MIN_LANGUAGES = 1;
export const ONBOARDING_MAX_LANGUAGES = 8;

/** Toggle id for “Other” — not stored; use `otherLanguagesText` instead. */
export const ONBOARDING_OTHER_LANGUAGE_ID = "__other_language__";

/** Nationality shortcut: pick “Other” then specify in text. */
export const ONBOARDING_OTHER_COUNTRY_ID = "__other_country__";

export const ONBOARDING_INTERESTS = [
  { id: "adventure", label: "Adventure" },
  { id: "beach", label: "Beach" },
  { id: "mountains", label: "Mountains" },
  { id: "city", label: "City Life" },
  { id: "nature", label: "Nature" },
  { id: "culture", label: "Culture" },
  { id: "food", label: "Food & Dining" },
  { id: "nightlife", label: "Nightlife" },
  { id: "photography", label: "Photography" },
  { id: "wildlife", label: "Wildlife" },
  { id: "history", label: "History" },
  { id: "art", label: "Art & Museums" },
] as const;

/** Widely spoken languages (preset chips). Custom entries go via Other + specify. */
export const ONBOARDING_LANGUAGES: ReadonlyArray<{ id: string; label: string }> = [
  { id: "english", label: "English" },
  { id: "mandarin_chinese", label: "Mandarin Chinese" },
  { id: "hindi", label: "Hindi" },
  { id: "spanish", label: "Spanish" },
  { id: "french", label: "French" },
  { id: "arabic", label: "Arabic" },
  { id: "bengali", label: "Bengali" },
  { id: "portuguese", label: "Portuguese" },
  { id: "russian", label: "Russian" },
  { id: "urdu", label: "Urdu" },
  { id: "indonesian", label: "Indonesian" },
  { id: "german", label: "German" },
  { id: "japanese", label: "Japanese" },
  { id: "swahili", label: "Swahili" },
  { id: "marathi", label: "Marathi" },
  { id: "telugu", label: "Telugu" },
  { id: "turkish", label: "Turkish" },
  { id: "tamil", label: "Tamil" },
  { id: "vietnamese", label: "Vietnamese" },
  { id: "korean", label: "Korean" },
  { id: "italian", label: "Italian" },
  { id: "thai", label: "Thai" },
  { id: "gujarati", label: "Gujarati" },
  { id: "polish", label: "Polish" },
  { id: "ukrainian", label: "Ukrainian" },
  { id: "persian_farsi", label: "Persian (Farsi)" },
  { id: "malay", label: "Malay" },
  { id: "kannada", label: "Kannada" },
  { id: "odia", label: "Odia" },
  { id: "malayalam", label: "Malayalam" },
  { id: "burmese", label: "Burmese" },
  { id: "romanian", label: "Romanian" },
  { id: "dutch", label: "Dutch" },
  { id: "greek", label: "Greek" },
  { id: "hungarian", label: "Hungarian" },
  { id: "czech", label: "Czech" },
  { id: "swedish", label: "Swedish" },
  { id: "hebrew", label: "Hebrew" },
  { id: "tagalog_filipino", label: "Tagalog / Filipino" },
  { id: "uzbek", label: "Uzbek" },
  { id: "punjabi", label: "Punjabi" },
  { id: "javanese", label: "Javanese" },
  { id: "hausa", label: "Hausa" },
  { id: "serbian", label: "Serbian" },
  { id: "croatian", label: "Croatian" },
  { id: "bulgarian", label: "Bulgarian" },
  { id: "slovak", label: "Slovak" },
  { id: "danish", label: "Danish" },
  { id: "finnish", label: "Finnish" },
  { id: "norwegian", label: "Norwegian" },
  { id: "lithuanian", label: "Lithuanian" },
  { id: "latvian", label: "Latvian" },
  { id: "estonian", label: "Estonian" },
  { id: "irish", label: "Irish" },
  { id: "icelandic", label: "Icelandic" },
  { id: "georgian", label: "Georgian" },
  { id: "armenian", label: "Armenian" },
  { id: "albanian", label: "Albanian" },
  { id: "pashto", label: "Pashto" },
  { id: "sinhala", label: "Sinhala" },
  { id: "nepali", label: "Nepali" },
  { id: "khmer", label: "Khmer" },
  { id: "lao", label: "Lao" },
  { id: "mongolian", label: "Mongolian" },
  { id: "tibetan", label: "Tibetan" },
  { id: "amharic", label: "Amharic" },
  { id: "zulu", label: "Zulu" },
  { id: "afrikaans", label: "Afrikaans" },
  { id: "yoruba", label: "Yoruba" },
  { id: "igbo", label: "Igbo" },
  { id: "somali", label: "Somali" },
  { id: "shona", label: "Shona" },
  { id: "xhosa", label: "Xhosa" },
  { id: "catalan", label: "Catalan" },
  { id: "galician", label: "Galician" },
  { id: "basque", label: "Basque" },
  { id: "welsh", label: "Welsh" },
  { id: "scottish_gaelic", label: "Scottish Gaelic" },
  { id: "kurdish", label: "Kurdish" },
  { id: "assamese", label: "Assamese" },
  { id: "hmong", label: "Hmong" },
  { id: "quechua", label: "Quechua" },
  { id: "haitian_creole", label: "Haitian Creole" },
  { id: "maori", label: "Māori" },
  { id: "samoan", label: "Samoan" },
  { id: "fijian", label: "Fijian" },
  { id: "tongan", label: "Tongan" },
];

/** Common countries / territories — tap to fill, or use Other + specify. */
export const ONBOARDING_COUNTRY_SHORTCUTS: ReadonlyArray<{ id: string; label: string }> = [
  { id: "in", label: "India" },
  { id: "cn", label: "China" },
  { id: "us", label: "United States" },
  { id: "id", label: "Indonesia" },
  { id: "pk", label: "Pakistan" },
  { id: "ng", label: "Nigeria" },
  { id: "br", label: "Brazil" },
  { id: "bd", label: "Bangladesh" },
  { id: "ru", label: "Russia" },
  { id: "mx", label: "Mexico" },
  { id: "jp", label: "Japan" },
  { id: "et", label: "Ethiopia" },
  { id: "ph", label: "Philippines" },
  { id: "eg", label: "Egypt" },
  { id: "vn", label: "Vietnam" },
  { id: "cd", label: "DR Congo" },
  { id: "tr", label: "Turkey" },
  { id: "ir", label: "Iran" },
  { id: "de", label: "Germany" },
  { id: "th", label: "Thailand" },
  { id: "gb", label: "United Kingdom" },
  { id: "fr", label: "France" },
  { id: "tz", label: "Tanzania" },
  { id: "za", label: "South Africa" },
  { id: "it", label: "Italy" },
  { id: "ke", label: "Kenya" },
  { id: "kr", label: "South Korea" },
  { id: "co", label: "Colombia" },
  { id: "es", label: "Spain" },
  { id: "ar", label: "Argentina" },
  { id: "dz", label: "Algeria" },
  { id: "ua", label: "Ukraine" },
  { id: "iq", label: "Iraq" },
  { id: "ca", label: "Canada" },
  { id: "ma", label: "Morocco" },
  { id: "pl", label: "Poland" },
  { id: "sa", label: "Saudi Arabia" },
  { id: "uz", label: "Uzbekistan" },
  { id: "my", label: "Malaysia" },
  { id: "af", label: "Afghanistan" },
  { id: "ve", label: "Venezuela" },
  { id: "pe", label: "Peru" },
  { id: "gh", label: "Ghana" },
  { id: "ye", label: "Yemen" },
  { id: "mz", label: "Mozambique" },
  { id: "np", label: "Nepal" },
  { id: "au", label: "Australia" },
  { id: "nl", label: "Netherlands" },
  { id: "ch", label: "Switzerland" },
  { id: "se", label: "Sweden" },
  { id: "be", label: "Belgium" },
  { id: "gr", label: "Greece" },
  { id: "cz", label: "Czech Republic" },
  { id: "pt", label: "Portugal" },
  { id: "hu", label: "Hungary" },
  { id: "il", label: "Israel" },
  { id: "at", label: "Austria" },
  { id: "ae", label: "United Arab Emirates" },
  { id: "cl", label: "Chile" },
  { id: "sg", label: "Singapore" },
  { id: "nz", label: "New Zealand" },
  { id: "ie", label: "Ireland" },
  { id: "hr", label: "Croatia" },
  { id: "ba", label: "Bosnia and Herzegovina" },
  { id: "rs", label: "Serbia" },
  { id: "fi", label: "Finland" },
  { id: "no", label: "Norway" },
  { id: "dk", label: "Denmark" },
  { id: "sk", label: "Slovakia" },
  { id: "lt", label: "Lithuania" },
  { id: "si", label: "Slovenia" },
  { id: "lv", label: "Latvia" },
  { id: "ee", label: "Estonia" },
  { id: "ge", label: "Georgia" },
  { id: "by", label: "Belarus" },
  { id: "hn", label: "Honduras" },
  { id: "bo", label: "Bolivia" },
  { id: "cu", label: "Cuba" },
  { id: "pa", label: "Panama" },
  { id: "cr", label: "Costa Rica" },
  { id: "pr", label: "Puerto Rico" },
  { id: "tw", label: "Taiwan" },
  { id: "hk", label: "Hong Kong" },
  { id: "mo", label: "Macau" },
  { id: "qa", label: "Qatar" },
  { id: "kw", label: "Kuwait" },
  { id: "bh", label: "Bahrain" },
  { id: "om", label: "Oman" },
  { id: "jo", label: "Jordan" },
  { id: "lb", label: "Lebanon" },
  { id: "ly", label: "Libya" },
  { id: "sd", label: "Sudan" },
  { id: "so", label: "Somalia" },
  { id: "zw", label: "Zimbabwe" },
  { id: "bw", label: "Botswana" },
  { id: "na", label: "Namibia" },
  { id: "mu", label: "Mauritius" },
  { id: "mv", label: "Maldives" },
  { id: "lk", label: "Sri Lanka" },
  { id: ONBOARDING_OTHER_COUNTRY_ID, label: "Other" },
];
